services:
  mongodb:
    image: mongo
    container_name: fast-delivery-db
    ports:
      - "27017:27017"

  backend:
    build: .
    container_name: fast-delivery-backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CORS_URL=${CORS_URL}
      - URL=${URL}
    depends_on:
      - mongodb
    volumes:
      - .:/back
